name: PyBannerGenie Tests

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyfiglet colorama pillow flake8 unittest

      - name: Run tests
        run: |
          python -m unittest discover -s tests -p 'test*.py'
          # If you don't have unit tests, you can run the tool directly
          python src/PyBannerGenie.py -i

      - name: Check for errors
        run: |
          if [ $? -ne 0 ]; then
            echo "Tests failed"
            exit 1
          fi
